# Simulation Parameter
gui: true                               # Show GUI Simulation
show_velocity: true
show_sensing: false
show_id: false
show_obstacles: false
show_bounding: true
world: 10                               # World size
seed: 1                                 # Random Seed
iterations: 20000             # Maximum of iterations
sensing: 0.8                       # Maximum sensing range
safezone: 0.8                    # Safezone range
velocity: 1.0                      # Max velocity
dt:  0.02                              # Sim steps
babystep: false                # Step by step simulation
log: true                            # Enable logging